# Linear Regression - Normal equation

## 머신러닝의 학습방법들
- Gradient descent based learning : 실제 값과 학습된 모델 예측치의 오차를 최소화 하여 모델의 추적 parameter 찾기가 목적  
- Probability theory based learning
- Information theory based learning
- Distance similarity based learning

## 1. Import Modules

In [1]:
import pandas as pd
import numpy as np

## 2. Load Dataset - simple variable

In [2]:
df = pd.read_csv('./normal_equation/test.csv')
df.head()

x          y
0  77  79.775152
1  21  23.177279
2  22  25.609262
3  20  17.857388
4  36  41.849864

In [3]:
X = df['x'].values.reshape(-1, 1)
y = df['y'].values

## 3. Build Model

In [4]:
import normal_equation.normal_equation_lr
import imp
imp.reload(normal_equation.normal_equation_lr)

<module 'normal_equation.normal_equation_lr' from 'C:\\Users\\박준형\\Python for Marchine Learning\\normal_equation\\normal_equation_lr.py'>

In [5]:
# def __init__
lr = normal_equation.normal_equation_lr.LinearRegression(fit_intercept = True)

In [6]:
lr.fit(X, y) # 접합

In [7]:
lr.intercept # 절편

-0.461810773661

In [8]:
lr.coef # 계수

array([1.01433536])

In [9]:
lr.predict(X)[:10]

array([77.64201157, 20.83923168, 21.85356704, 19.82489633, 36.05426201,
       14.75321955, 62.42698124, 95.90004796, 19.82489633,  4.609866  ])

## 4. Validation
직접 만든 Linear Regerssion과 sklearn의 Linear Regression이 같을까?

In [11]:
from sklearn import linear_model
sk_lr = linear_model.LinearRegression(normalize = False)

In [12]:
sk_lr.fit(X, y)

LinearRegression()

In [14]:
sk_lr.intercept_

-0.4618107736611563

In [16]:
import numpy.testing as npt
npt.assert_almost_equal(sk_lr.intercept_, lr.intercept)

In [21]:
sk_lr.coef_

array([1.01433536])

In [22]:
lr._coef

array([1.01433536])

In [23]:
np.isclose(lr.coef, sk_lr.coef_)

array([ True])

In [26]:
X_test = df['x'].values.reshape(-1, 1)

In [27]:
lr.predict(X_test)[:5]

array([77.64201157, 20.83923168, 21.85356704, 19.82489633, 36.05426201])

In [28]:
sk_lr.predict(X_test)[:5]

array([77.64201157, 20.83923168, 21.85356704, 19.82489633, 36.05426201])